"""Add audit fields to all tables

Revision ID: bacddf8094d4
Revises: 31d141bf7e1b
Create Date: 2025-07-07 13:55:47.569540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacddf8094d4'
down_revision = '31d141bf7e1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coffee', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('coffee', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('coffee', sa.Column('deleted_by', sa.String(length=255), nullable=True))
    op.add_column('coffee', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('flavortag', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('flavortag', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('flavortag', sa.Column('deleted_by', sa.String(length=255), nullable=True))
    op.add_column('flavortag', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('roaster', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('roaster', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('roaster', sa.Column('deleted_by', sa.String(length=255), nullable=True))
    op.add_column('roaster', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('tasting_note', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('tasting_note', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('tasting_note', sa.Column('deleted_by', sa.String(length=255), nullable=True))
    op.add_column('tasting_note', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('tasting_session', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('tasting_session', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('tasting_session', sa.Column('deleted_by', sa.String(length=255), nullable=True))
    op.add_column('tasting_session', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasting_session', 'deleted_at')
    op.drop_column('tasting_session', 'deleted_by')
    op.drop_column('tasting_session', 'updated_by')
    op.drop_column('tasting_session', 'created_by')
    op.drop_column('tasting_note', 'deleted_at')
    op.drop_column('tasting_note', 'deleted_by')
    op.drop_column('tasting_note', 'updated_by')
    op.drop_column('tasting_note', 'created_by')
    op.drop_column('roaster', 'deleted_at')
    op.drop_column('roaster', 'deleted_by')
    op.drop_column('roaster', 'updated_by')
    op.drop_column('roaster', 'created_by')
    op.drop_column('flavortag', 'deleted_at')
    op.drop_column('flavortag', 'deleted_by')
    op.drop_column('flavortag', 'updated_by')
    op.drop_column('flavortag', 'created_by')
    op.drop_column('coffee', 'deleted_at')
    op.drop_column('coffee', 'deleted_by')
    op.drop_column('coffee', 'updated_by')
    op.drop_column('coffee', 'created_by')
    # ### end Alembic commands ###