"""Initial migration: coffee tasting schema

Revision ID: 0ca0ad41b915
Revises:
Create Date: 2025-06-22 14:44:28.571963

"""


# revision identifiers, used by Alembic.
revision = '0ca0ad41b915'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
