-- Migration: Create user roles table for RBAC
-- Run this in Supabase SQL Editor (Dashboard > SQL Editor)

-- Step 1: Create the app_role enum type
create type public.app_role as enum ('admin', 'user');

-- Step 2: Create the user_roles table
create table public.user_roles (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users on delete cascade not null,
    role app_role not null default 'user',
    created_at timestamptz default now() not null,
    unique (user_id, role)
);

-- Step 3: Add table comment
comment on table public.user_roles is 'Application roles for each user.';

-- Step 4: Enable RLS on the table
alter table public.user_roles enable row level security;

-- Step 5: Create policy for users to read their own roles
create policy "Users can view their own roles"
    on public.user_roles
    for select
    to authenticated
    using (auth.uid() = user_id);

-- Step 6: Create policy for admins to manage all roles
-- (This will work once we have the auth hook in place)
create policy "Admins can manage all roles"
    on public.user_roles
    for all
    to authenticated
    using (
        exists (
            select 1 from public.user_roles
            where user_id = auth.uid() and role = 'admin'
        )
    );

-- Step 7: Create index for faster lookups
create index idx_user_roles_user_id on public.user_roles(user_id);
